# Generated by Django 4.1.2 on 2023-01-12 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'カテゴリテーブル',
                'verbose_name_plural': 'カテゴリテーブル',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img.category')),
            ],
            options={
                'verbose_name': 'ブログテーブル',
                'verbose_name_plural': 'ブログテーブル',
            },
        ),
    ]
