# Generated by Django 4.1.2 on 2023-01-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_remove_question_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='question_text',
            new_name='title',
        ),
    ]
